import { QuizQuestion } from '../../types/test';

export const quizQuestions: QuizQuestion[] = [
  {
    id: 1,
    questionKey: 'quiz.q1.title',
    options: [
      { id: 'A', labelKey: 'quiz.q1.options.A' },
      { id: 'B', labelKey: 'quiz.q1.options.B' },
      { id: 'C', labelKey: 'quiz.q1.options.C' },
      { id: 'D', labelKey: 'quiz.q1.options.D' },
      { id: 'E', labelKey: 'quiz.q1.options.E' },
      { id: 'F', labelKey: 'quiz.q1.options.F' },
    ],
  },
  {
    id: 2,
    questionKey: 'quiz.q2.title',
    options: [
      { id: 'A', labelKey: 'quiz.q2.options.A' },
      { id: 'B', labelKey: 'quiz.q2.options.B' },
      { id: 'C', labelKey: 'quiz.q2.options.C' },
      { id: 'D', labelKey: 'quiz.q2.options.D' },
      { id: 'E', labelKey: 'quiz.q2.options.E' },
      { id: 'F', labelKey: 'quiz.q2.options.F' },
    ],
  },
  {
    id: 3,
    questionKey: 'quiz.q3.title',
    options: [
      { id: 'A', labelKey: 'quiz.q3.options.A' },
      { id: 'B', labelKey: 'quiz.q3.options.B' },
      { id: 'C', labelKey: 'quiz.q3.options.C' },
      { id: 'D', labelKey: 'quiz.q3.options.D' },
      { id: 'E', labelKey: 'quiz.q3.options.E' },
      { id: 'F', labelKey: 'quiz.q3.options.F' },
    ],
  },
  {
    id: 4,
    questionKey: 'quiz.q4.title',
    options: [
      { id: 'A', labelKey: 'quiz.q4.options.A' },
      { id: 'B', labelKey: 'quiz.q4.options.B' },
      { id: 'C', labelKey: 'quiz.q4.options.C' },
      { id: 'D', labelKey: 'quiz.q4.options.D' },
      { id: 'E', labelKey: 'quiz.q4.options.E' },
      { id: 'F', labelKey: 'quiz.q4.options.F' },
    ],
  },
  {
    id: 5,
    questionKey: 'quiz.q5.title',
    options: [
      { id: 'A', labelKey: 'quiz.q5.options.A' },
      { id: 'B', labelKey: 'quiz.q5.options.B' },
      { id: 'C', labelKey: 'quiz.q5.options.C' },
      { id: 'D', labelKey: 'quiz.q5.options.D' },
      { id: 'E', labelKey: 'quiz.q5.options.E' },
      { id: 'F', labelKey: 'quiz.q5.options.F' },
    ],
  },
  {
    id: 6,
    questionKey: 'quiz.q6.title',
    options: [
      { id: 'A', labelKey: 'quiz.q6.options.A' },
      { id: 'B', labelKey: 'quiz.q6.options.B' },
      { id: 'C', labelKey: 'quiz.q6.options.C' },
      { id: 'D', labelKey: 'quiz.q6.options.D' },
      { id: 'E', labelKey: 'quiz.q6.options.E' },
      { id: 'F', labelKey: 'quiz.q6.options.F' },
    ],
  },
  {
    id: 7,
    questionKey: 'quiz.q7.title',
    options: [
      { id: 'A', labelKey: 'quiz.q7.options.A' },
      { id: 'B', labelKey: 'quiz.q7.options.B' },
      { id: 'C', labelKey: 'quiz.q7.options.C' },
      { id: 'D', labelKey: 'quiz.q7.options.D' },
      { id: 'E', labelKey: 'quiz.q7.options.E' },
      { id: 'F', labelKey: 'quiz.q7.options.F' },
    ],
  },
  {
    id: 8,
    questionKey: 'quiz.q8.title',
    options: [
      { id: 'A', labelKey: 'quiz.q8.options.A' },
      { id: 'B', labelKey: 'quiz.q8.options.B' },
      { id: 'C', labelKey: 'quiz.q8.options.C' },
      { id: 'D', labelKey: 'quiz.q8.options.D' },
      { id: 'E', labelKey: 'quiz.q8.options.E' },
      { id: 'F', labelKey: 'quiz.q8.options.F' },
    ],
  },
  {
    id: 9,
    questionKey: 'quiz.q9.title',
    options: [
      { id: 'A', labelKey: 'quiz.q9.options.A' },
      { id: 'B', labelKey: 'quiz.q9.options.B' },
      { id: 'C', labelKey: 'quiz.q9.options.C' },
      { id: 'D', labelKey: 'quiz.q9.options.D' },
      { id: 'E', labelKey: 'quiz.q9.options.E' },
      { id: 'F', labelKey: 'quiz.q9.options.F' },
    ],
  },
  {
    id: 10,
    questionKey: 'quiz.q10.title',
    options: [
      { id: 'A', labelKey: 'quiz.q10.options.A' },
      { id: 'B', labelKey: 'quiz.q10.options.B' },
      { id: 'C', labelKey: 'quiz.q10.options.C' },
      { id: 'D', labelKey: 'quiz.q10.options.D' },
      { id: 'E', labelKey: 'quiz.q10.options.E' },
      { id: 'F', labelKey: 'quiz.q10.options.F' },
    ],
  },
  {
    id: 11,
    questionKey: 'quiz.q11.title',
    options: [
      { id: 'A', labelKey: 'quiz.q11.options.A' },
      { id: 'B', labelKey: 'quiz.q11.options.B' },
      { id: 'C', labelKey: 'quiz.q11.options.C' },
      { id: 'D', labelKey: 'quiz.q11.options.D' },
      { id: 'E', labelKey: 'quiz.q11.options.E' },
      { id: 'F', labelKey: 'quiz.q11.options.F' },
    ],
  },
  {
    id: 12,
    questionKey: 'quiz.q12.title',
    options: [
      { id: 'A', labelKey: 'quiz.q12.options.A' },
      { id: 'B', labelKey: 'quiz.q12.options.B' },
      { id: 'C', labelKey: 'quiz.q12.options.C' },
      { id: 'D', labelKey: 'quiz.q12.options.D' },
      { id: 'E', labelKey: 'quiz.q12.options.E' },
      { id: 'F', labelKey: 'quiz.q12.options.F' },
    ],
  },
  {
    id: 13,
    questionKey: 'quiz.q13.title',
    options: [
      { id: 'A', labelKey: 'quiz.q13.options.A' },
      { id: 'B', labelKey: 'quiz.q13.options.B' },
      { id: 'C', labelKey: 'quiz.q13.options.C' },
      { id: 'D', labelKey: 'quiz.q13.options.D' },
      { id: 'E', labelKey: 'quiz.q13.options.E' },
      { id: 'F', labelKey: 'quiz.q13.options.F' },
    ],
  },
  {
    id: 14,
    questionKey: 'quiz.q14.title',
    options: [
      { id: 'A', labelKey: 'quiz.q14.options.A' },
      { id: 'B', labelKey: 'quiz.q14.options.B' },
      { id: 'C', labelKey: 'quiz.q14.options.C' },
      { id: 'D', labelKey: 'quiz.q14.options.D' },
      { id: 'E', labelKey: 'quiz.q14.options.E' },
      { id: 'F', labelKey: 'quiz.q14.options.F' },
    ],
  },
  {
    id: 15,
    questionKey: 'quiz.q15.title',
    options: [
      { id: 'A', labelKey: 'quiz.q15.options.A' },
      { id: 'B', labelKey: 'quiz.q15.options.B' },
      { id: 'C', labelKey: 'quiz.q15.options.C' },
      { id: 'D', labelKey: 'quiz.q15.options.D' },
      { id: 'E', labelKey: 'quiz.q15.options.E' },
      { id: 'F', labelKey: 'quiz.q15.options.F' },
    ],
  },
];
